version: '3.0'
services:
  nodejs:
    build:
      context: .
      dockerfile: node.dockerfile
    container_name: nodejs
    restart: unless-stopped
    ports:
    - "1337"
  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - nodejs
