version: '3.0'
services:
  nodejs:
    build:
      context: .
      dockerfile: node.dockerfile
    container_name: nodejs
    restart: unless-stopped
    command: npm run dev
    volumes:
    - ./app/app:/usr/src/app/app
    ports:
    - "1337"
  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - nodejs
  db:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: app
  redis:
    image: redis
    ports:
    - "6379"

