version: '3.0'
services:
  server:
    build:
      context: ./app/server/
    container_name: server
    restart: unless-stopped
    command: npm run dev
    volumes:
    - ./app/server:/usr/app
    - /usr/app/node_modules
#    ports:
#    - "9000"
  client:
    build:
      context: ./app/client/
    container_name: client
    volumes:
    - ./app/client/:/usr/app
    - /usr/app/node_modules
    depends_on:
      - server
    ports:
    - "3000:3000"
    stdin_open: true
    restart: unless-stopped
  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - server
  db:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: app
  redis:
    image: redis
    ports:
    - "6379"

